source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'Volumer_Example', :exclusive => true do
  pod "Volumer", :path => "../"
end

target 'Volumer_Tests', :exclusive => true do
  pod "Volumer", :path => "../"

  
end
